# API Keys
[cima]
base_url = "https://cima.aemps.es/cima/rest/"
rate_limit = 0.5

[whatsapp]
api_key = "tu_whatsapp_api_key"
webhook_token = "tu_webhook_token"

[models]
yolo_model_path = "runs/detect/yolov10_train6/weights/best.pt"
